finished hw
rgnap1/Homework-2.1 pull request #1
Opened 2023-01-12 16:11 UTC by rgnap1

2023-01-15 19:01 UTC, OlgaLugacheva requested changes

2023-01-15 19:01 UTC, OlgaLugacheva commented on src/transport/Car.java
> +
кое -где забыла модификатор доступа

2023-02-06 19:54 UTC, zrazzhivin commented on src/Main.java
> +                truck.goDiagnostics();
при текущем подходе нет гарантий чтобы мы попробуем пройти диагностику всех перечисленных объектов. Упадет эксепшен на первом? Сразу перейдем в catch блок. 

Лучше каждый вызов диагностики обернуть в свой try / catch. Чтобы не дублировать код можно применить цикл.

2023-02-07 08:06 UTC, OlgaLugacheva requested changes

2023-02-07 08:06 UTC, OlgaLugacheva commented on src/transport/STO.java
> +Queue<Transport> queue;
модификатор ?

2023-02-15 16:13 UTC, merged